### ISSUE TITLE
Error when markdown missing top level header

### ISSUE THREAD

**Issue by Dumtard** [iamjackg/md2cf#4]
The markdown requires a top level header `# Header` to create the page title. This should not be required to be considered valid markdown.

This line assumes h1 exists.
```    page_title = soup.h1.text or file_name```

Here is the resulting error.
```
Traceback (most recent call last):
  File "/home/charles/.local/bin/md2cf", line 11, in <module>
    sys.exit(main())
  File "/home/charles/.local/lib/python3.6/site-packages/md2cf/__main__.py", line 91, in main
    page_data = page_data_from_file_name(file_name)
  File "/home/charles/.local/lib/python3.6/site-packages/md2cf/__main__.py", line 49, in page_data_from_file_name
    page_title = soup.h1.text or file_name
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by iamjackg** [comment]
Thanks! This is now fixed.
