### ISSUE TITLE
folder upload breaks when --no-gitignore is omitted

### ISSUE THREAD

**Issue by petermefrandsen** [iamjackg/md2cf#60]
I have a MkDocs project with documentation available, for this I have a .gitignore file for python.

However when I target a folder the action fails when I omit the --no-gitignore flag.

:x: `Run md2cf --host 'https://petermefrandsen.atlassian.net/wiki/rest/api' --username *** -*** --space 'md2cf' ./docs`
[GitHub action job](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043527881/jobs/6952549020)

:heavy_check_mark: `Run md2cf --host 'https://petermefrandsen.atlassian.net/wiki/rest/api' --username *** -*** --space 'md2cf' --no-gitignore ./docs` 
[GitHub action job](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043548630/jobs/6952596886)

``` bash
Run md2cf --host 'https://petermefrandsen.atlassian.net/wiki/rest/api' --username *** -*** --space 'md[2](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043527881/jobs/6952549020#step:5:2)cf' ./docs
  md2cf --host 'https://petermefrandsen.atlassian.net/wiki/rest/api' --username *** -*** --space 'md2cf' ./docs
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043527881/jobs/6952549020#step:5:3).11.1/x6[4](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043527881/jobs/6952549020#step:5:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.1/x64/lib
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.1/x64/bin/md2cf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/md2cf/__main__.py", line 403, in main
    pages_to_upload = collect_pages_to_upload(args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/md2cf/__main__.py", line [5](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043527881/jobs/6952549020#step:5:5)15, in collect_pages_to_upload
    pages_to_upload += md2cf.document.get_pages_from_directory(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x[6](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043527881/jobs/6952549020#step:5:6)4/lib/python3.11/site-packages/md2cf/document.py", line 109, in get_pages_from_directory
    markdown_files = [
                     ^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/md2cf/document.py", line 110, in <listcomp>
    path for path in markdown_files if not git_repo.is_ignored(path)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/md2cf/ignored_files.py", line 85, in is_ignored
    return any([m(filepath) for m in matchers])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/md2cf/ignored_files.py", line 85, in <listcomp>
    return any([m(filepath) for m in matchers])
                ^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/gitignore_parser.py", line 32, in <lambda>
    return lambda file_path: any(r.match(file_path) for r in rules)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/gitignore_parser.py", line 32, in <genexpr>
    return lambda file_path: any(r.match(file_path) for r in rules)
                                 ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/gitignore_parser.py", line 143, in match
    if re.search(self.regex, rel_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/re/__init__.py", line 1[7](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043527881/jobs/6952549020#step:5:8)6, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/re/_parser.py", line 9[8](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043527881/jobs/6952549020#step:5:9)0, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.[11](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043527881/jobs/6952549020#step:5:12).1/x64/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/re/_parser.py", line 8[41](https://github.com/petermefrandsen/mkdocs-deployment/actions/runs/4043527881/jobs/6952549020#step:5:42), in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 1
Error: Process completed with exit code 1.
```

**Comment by iamjackg** [comment]
Ah, this seems to be an issue with the upstream `gitignore_parser` module and Python 3.11 because of python/cpython#91222. I'll see if I can do something about it, but the function that's generating the regex in that module is pretty bonkers.

**Comment by petermefrandsen** [comment]
Sounds great - until then I'll just do it with the workaround setting the flag.

**Comment by iamjackg** [comment]
Hey, I just pushed an alpha version of v2 -- it has some breaking changes in the output format (https://github.com/iamjackg/md2cf/tree/develop#terminal-output-format), but includes a fix for this issue. Can you give it a whirl and let me know if it's fine?

It's at https://pypi.org/project/md2cf/2.0.0a0/ and you can install it with

```bash
pip install md2cf --pre
```

**Comment by petermefrandsen** [comment]
Works splendidly!

**Comment by iamjackg** [comment]
[v2.0.0](https://github.com/iamjackg/md2cf/releases/tag/v2.0.0) is out :) Closing this.
